apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jgwest-tenant/devfile-sample/devfile-sample@sha256:8e09bc86a8d0b13a8a915b8f12455cb8d0b3c399f27299d2509e74cc844af687
        name: my-nodejs
        resources: {}
status: {}
